apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:8.16.3
        imagePullPolicy: Always
        env:

        - name: DEBUG
          value: "false"

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: 0cFw81^&UOIkt1h^Enk%iJ28bSNjlflDF@@kfGHq8GbT!A^GZiwepfbAgeBviz2E
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: K68xSo6O3gxb12ehgXOooz3Hh3ut5u!q5RtEK6x1i0Hm@tGfh8gfaHv47jH1C94q
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: XrZ666NxxLY7u1Xgsinza8OTg3An%wQl%X@CcIYiko#^BedwWZgjb&g*eIMvlPVb

        - name: GITLAB_ROOT_PASSWORD
          value: s4y2Uc%r#GfGpaOnh1lH
        - name: GITLAB_ROOT_EMAIL
          value: root@example.com

        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "1022"

        - name: SSL_SELF_SIGNED
          value: "true"
        - name: SSL_CERTIFICATE_PATH
          value: "/vagrant/certs/gitlab.crt"
        - name: SSL_KEY_PATH
          value: "/vagrant/certs/gitlab.key"
        - name: SSL_DHPARAM_PATH
          value: "/vagrant/certs/dhparam.pem"

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: gitlab-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: 8Br55n@e0$Jw6W39@6OlTWKY%N$4IlsiOi!h
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: gitlab-redis
        - name: REDIS_PORT
          value: "6379"

        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1

      volumes:
      - name: data
        emptyDir: {}
