apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-three
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-three
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-three
                port:
                  number: 80
