Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	
	config.vm.hostname = "mesafiS"

	config.vm.network "private_network", ip: "192.168.42.110"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "mesafiS"
		vb.memory = "2048"
		vb.cpus = 2
	end

	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 664 --flannel-iface eth1 && kubectl apply -f /vagrant/confs/
	SHELL
end
