Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	
	config.vm.hostname = "mesafiS"

	config.vm.network "private_network", ip: "192.168.42.110"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "mesafiS"
		vb.memory = "1024"
		vb.cpus = 1
	end

	config.vm.provision "shell", inline: <<-SHELL
		curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 664 --flannel-iface eth1
	SHELL
end