Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	
	config.vm.define "mesafiS" do |control|
		control.vm.hostname = "mesafiS"

		control.vm.network "private_network", ip: "192.168.42.110"

		control.vm.provider "virtualbox" do |vb|
			vb.name = "mesafiS"
			vb.memory = "1024"
			vb.cpus = 1
		end

		control.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 664 --flannel-iface eth1
		SHELL

		control.trigger.after :up do |trigger|
			trigger.run = {inline: "bash -c 'vagrant ssh mesafiS -c \"sudo cat /var/lib/rancher/k3s/server/node-token\" > token'"}
		end
	end
	
	config.vm.define "mesafiSW" do |control|
		control.vm.hostname = "mesafiSW"

		control.vm.network "private_network", ip: "192.168.42.111"

		control.vm.provider "virtualbox" do |vb|
			vb.name = "mesafiSW"
			vb.memory = "1024"
			vb.cpus = 1
		end
		
		control.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - agent --server https://192.168.42.110:6443 --token-file /vagrant/token --flannel-iface eth1
		SHELL
	end

	config.vm.provision "shell" do |s|
		ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
		s.inline = <<-SHELL
			echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
		SHELL
	end
end
