Vagrant.configure("2") do |config|
	config.vm.box = "generic/centos8"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "mesafi"
		vb.memory = "512"
		vb.cpus = 1
	end

	config.vm.define "mesafiS" do |controller|
		controller.vm.hostname = "mesafiS"

		controller.vm.network "private_network", ip: "192.168.42.110"

		controller.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -
		SHELL
	end

	config.vm.define "mesafiSW" do |agent|
		agent.vm.hostname = "mesafiSW"

		agent.vm.network "private_network", ip: "192.168.42.111"

		agent.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -
		SHELL
	end
end
