Vagrant.configure("2") do |config|
  #config.vm.name = "gitlab"
	
	config.vm.box = "ubuntu/trusty64"
	
	#config.vm.synced_folder ".", "/vagrant"
	
	config.vm.network "public_network", ip: "10.12.100.102", bridge: "en0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "gitlab"
		vb.hostname = "gitlab1337"
		vb.gui = false
    vb.memory = "3072"
		vb.cpus = "2"
  end

	config.vm.provision "shell", inline: <<-SHELL
  SHELL
end
