Vagrant.configure("2") do |config|
	#config.vm.name = "gitlab"

	config.vm.box = "ubuntu/xenial64"

	config.vm.network "public_network", bridge: "wlo1"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "gitlab"
		vb.memory = "4096"
		vb.cpus = "4"
	end

	config.vm.provision "shell", inline: <<-SHELL
		cd /vagrant;
		#bash setup.sh;
		sudo bash k3s.sh;
	SHELL
end
