apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
spec:
  type: LoadBalancer
  selector:
    name: gitlab
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: ssh
      port: 1022
      targetPort: ssh
